In [2]:
import numpy as np

In [4]:
arr = np.array([10,200,300])
arr1 = np.insert(arr, 1, 20)

In [8]:
arr

array([ 10, 200, 300])

In [10]:
arr1

array([ 10,  20, 200, 300])

In [13]:
arr1.ndim

1

In [16]:
arr1.sum()

530

In [23]:
arr2 = np.array([[10,20], [40,20]])
arr2.sum()

90

In [24]:
arr2.sum(axis=1)

array([30, 60])

In [22]:
arr2.sum(axis=0)

array([50, 40])

In [26]:
arr2

array([[10, 20],
       [40, 20]])

In [27]:
np.insert(arr2, 2, 1)

array([10, 20,  1, 40, 20])

In [29]:
np.insert(arr2, 2, 1, axis=0)

array([[10, 20],
       [40, 20],
       [ 1,  1]])

In [30]:
np.insert(arr2, 2, 1, axis=1)

array([[10, 20,  1],
       [40, 20,  1]])