In [2]:
import numpy as np

In [4]:
a = np.array([{1, 2}, {3, 4}])

In [31]:
np.array_split(a, 1)

[array([{1, 2}, {3, 4}], dtype=object)]

In [32]:
np.array_split(a, 2)

[array([{1, 2}], dtype=object), array([{3, 4}], dtype=object)]

In [33]:
np.array_split(a, 2,axis=0)

[array([{1, 2}], dtype=object), array([{3, 4}], dtype=object)]

In [53]:
b = np.array([[1,2,0], [3,4,0], [5,6,0]])
b

array([[1, 2, 0],
       [3, 4, 0],
       [5, 6, 0]])

In [60]:
np.array_split(b, 3, axis=1)

[array([[1],
        [3],
        [5]]),
 array([[2],
        [4],
        [6]]),
 array([[0],
        [0],
        [0]])]