In [2]:
import numpy

In [5]:
a = numpy.array([10, 20, 30, 40])
a

array([10, 20, 30, 40])

In [4]:
type(a)

numpy.ndarray

In [7]:
b = numpy.array([[1, 2], [3, 4]])
b

array([[1, 2],
       [3, 4]])

In [10]:
print(b[1][1])

4


In [9]:
print(b[-1][-1])

4


In [12]:
print(b[0, :])

[1 2]


In [13]:
print(b[:, 1])

[2 4]


In [14]:
b.transpose()

array([[1, 3],
       [2, 4]])

In [16]:
s1 = numpy.array([[1, 2], [3, 4]])

In [17]:
s2 = numpy.array([[5, 6], [7, 8]])

In [21]:
s1 + s2

array([[ 6,  8],
       [10, 12]])

In [23]:
s1 - s2

array([[-4, -4],
       [-4, -4]])

In [24]:
s1 * s2

array([[ 5, 12],
       [21, 32]])

In [25]:
s1 / s2

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [26]:
a.sum()

100

In [27]:
a.argmax()

3

In [28]:
a.argmin()

0