In [2]:
import numpy as np

In [5]:
a = np.array([[0,1], [2,3]])
a

array([[0, 1],
       [2, 3]])

In [17]:
b = np.array([[5,6]])

In [19]:
np.concatenate((a, b), axis=0)

array([[0, 1],
       [2, 3],
       [5, 6]])

In [21]:
np.concatenate((a, b.T), axis=1)

array([[0, 1, 5],
       [2, 3, 6]])

In [24]:
np.linspace(2, 5, 5)

array([2.  , 2.75, 3.5 , 4.25, 5.  ])

In [27]:
np.unique(a)

array([0, 1, 2, 3])